# Generated by Django 5.1.3 on 2024-11-20 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='processed_by_logistician',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subdivision'),
        ),
    ]
