# Generated by Django 5.1.3 on 2024-11-16 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_request_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='dates',
            new_name='date_type_quantity_plannedWorkTime',
        ),
        migrations.RemoveField(
            model_name='request',
            name='plannedWorkTime',
        ),
        migrations.RemoveField(
            model_name='request',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='request',
            name='type',
        ),
    ]
